DDdd:
  value: test


server:
  port: 8070
  servlet:
    context-path: /admin
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.3.188:3306/mplus_log?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#    type: com.zaxxer.hikari.util.DriverDataSource
mybatis:
  type-aliases-package: org.com.dream.cloud.provider.mapper
  mapper-locations: classpath:mapper/*.xml