server:
  port: 8082
spring:
  application:
    name: provider-admin
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

    url: jdbc:mysql://192.168.3.188:3306/mplus_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
mybatis:
  type-aliases-package: org.com.dream.cloud.code.mapper
  mapper-locations: classpath:mapper/*.xml